sudo: required

language: go

services:
  - docker

env:
  - DOCKERTEST_BIND_LOCALHOST=true

go:
  - 1.6.3
  - 1.7

before_install:
  - go get -u github.com/tools/godep

install:
  - godep restore

script:
  - go test -v -race ./...