sudo: required

language: go

services:
  - mysql

os:
  - osx

go:
  - 1.6.3
  - 1.7

before_install:
  - go get -u github.com/tools/godep

install:
  - godep restore
  - mysql -uroot -e "create database osin"

script:
  - go test -v -race ./...